import { StyleSheet } from 'react-native';
import { Colors, Metrics, GlobalStyles } from '../GlobalStyles';

export const MyChargersStyles = StyleSheet.create({
  container: {
    ...GlobalStyles.container,
  },
  listContent: {
    padding: Metrics.padding,
    paddingBottom: 60,
  },
  card: {
    backgroundColor: Colors.white,
    borderRadius: 24,
    marginBottom: 20,
    flexDirection: 'row',
    height: 120,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.05)',
    ...GlobalStyles.shadow,
    elevation: 4,
  },
  imagePreview: {
    width: 110,
    height: '100%',
    backgroundColor: Colors.primaryLight,
  },
  statusBadge: {
    position: 'absolute',
    top: 10,
    left: 10,
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 12,
    zIndex: 10,
    ...GlobalStyles.shadow,
  },
  statusText: {
    fontSize: 10,
    fontWeight: '900',
    color: Colors.white,
    letterSpacing: 0.5,
  },
  infoContainer: {
    flex: 1,
    padding: 15,
    justifyContent: 'space-between',
  },
  address: {
    fontSize: 16,
    fontWeight: '800',
    color: Colors.dark,
  },
  specRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  specText: {
    fontSize: 13,
    color: Colors.gray,
    fontWeight: '600',
    marginLeft: 8,
  },
  actionsContainer: {
    flexDirection: 'column',
    backgroundColor: '#F8F9FA',
    width: 60,
    borderLeftWidth: 1,
    borderLeftColor: Colors.border,
  },
  actionButton: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  deleteButton: {
    borderTopWidth: 1,
    borderTopColor: Colors.border,
  },
  emptyContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 80,
    paddingHorizontal: 40,
  },
  emptyText: {
    fontSize: 16,
    color: Colors.gray,
    fontWeight: '600',
    textAlign: 'center',
    marginTop: 20,
    lineHeight: 24,
  },
  fab: {
    position: 'absolute',
    bottom: 30,
    right: 30,
    backgroundColor: Colors.primary,
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 8,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
  },
});